### ISSUE TITLE
Recommendation to use package with k8s v0.26.0

### ISSUE THREAD

**Issue by shahpratikr** [redhat-marketplace/redhat-marketplace-operator#377]
In `k8s.io/apimachinery v0.25.0` version, `k8s.io/apimachinery/pkg/util/clock` this package is removed. Redhat operator is using `k8s.io/apimachinery v0.23.0` version. Can you please share a recommendation to use redhat-marketplace-operator with `k8s.io/apimachinery v0.26.0` version?

**Comment by dacleyra** [comment]
Probably change to use `k8s.io/utils/clock`
redhat-marketplace-operator aligns with Openshift kubernetes releases.
When redhat-marketplace-operator is ready to support Openshift v4.11, it will use `k8s.io/apimachinery` v0.24

**Comment by shahpratikr** [comment]
@dacleyra we are using redhat-marketplace-operator as a dependency in our project. We wanted to switch to `k8s.io v0.26.0` version. is there any immediate plan for redhat-marketplace-operator to support v0.26.0 version?

**Comment by dacleyra** [comment]
clock is now updated in the latest release, but doing a go.mod replace => k8s.io v0.26.0 may still pose a problem as there are still some older apis used like v1beta1batch. vNext will stop using them, in order to bring us up to v0.24
