### ISSUE TITLE
Support for OpenShift >=4.11 in Red Hat Operator Hub

### ISSUE THREAD

**Issue by Feelas** [redhat-marketplace/redhat-marketplace-operator#410]
**Describe the issue**
It is impossible to use Red Hat Marketplace Operator on OpenShift versions >=4.11 despite no information about minor version constraints is provided in the documentation for the product. This is probably due to manifests upstreamed in https://github.com/redhat-openshift-ecosystem/certified-operators/pull/1815 having 4.8-4.10 version lock. Is the operator compatible with OpenShift up to 4.10 or is that an oversight in the upstreaming process?

Using the instructions for Red Hat OpenShift Marketplace found in https://marketplace.redhat.com/en-us/documentation/clusters theoretically works, but results in Subscription being unable to find the CatalogSource for OpenShift certified-operators. The operator is not installed in the end.

**To Reproduce**
1. Follow the installation of Red Hat OpenShift Marketplace (e.g. https://marketplace.redhat.com/en-us/documentation/clusters) on an OpenShift >= 4.11 cluster.
2. Verify that the subscription deployed in openshift-redhat-marketplace shows errors similar to the below:
```
Message:               constraints not satisfiable: no operators found in package redhat-marketplace-operator in the catalog referenced by subscription redhat-marketplace-operator, subscription redhat-marketplace-operator exists
```

**Expected behavior**
It is possible to use Red Hat Marketplace Operator on OpenShift >= 4.11 or a documentation notice about minor version incompatibility is explicitly made in the product documentation.

**OpenShift (please complete the following information):**
 - Version: >= 4.11

**Additional context**

**Log Output**
```$ oc describe sub redhat-marketplace-operator
  Conditions:
    Message:               constraints not satisfiable: no operators found in package redhat-marketplace-operator in the catalog referenced by subscription redhat-marketplace-operator, subscription redhat-marketplace-operator exists
    Reason:                ConstraintsNotSatisfiable
    Status:                True
    Type:                  ResolutionFailed
    Last Transition Time:  2023-03-03T11:46:01Z
    Message:               all available catalogsources are healthy
    Reason:                AllCatalogSourcesHealthy
    Status:                False
    Type:                  CatalogSourcesUnhealthy
```

**Comment by dacleyra** [comment]
The team is aware, and a release with v4.11 support is in progress

**Comment by Feelas** [comment]
@dacleyra thanks for the confirmation, will 4.12 support also be included in the same release or not?

**Comment by dacleyra** [comment]
Open Shift 4.12 support was added in v2.10.0, and Open Shift is currently supported 4.13 on latest
