### ISSUE TITLE
The imagePullPolicy is set to Always

### ISSUE THREAD

**Issue by danpawlik** [redhat-marketplace/redhat-marketplace-operator#604]
**Describe the bug**
The OpenStack K8S Operator [1] project is using CRC [2] for making the CI tests. Some of the pods created by the operator have `imagePullPolicy: Always` , which might break not just OpenStack K8S Operator CI, but also other users (the image is already present on the host, but the image policy forces to try to pull the newest image).

**Expected behavior**
The image policy would be set to `IfNotPresent`

**OpenShift (please complete the following information):**
 - Version: 4.13, 4.14 

[1] - https://github.com/openstack-k8s-operators
[2] - https://github.com/crc-org/crc

**Comment by dacleyra** [comment]
resolved in v2.15.0
